### ISSUE TITLE
It is an error to use tabs as crontab delimiters.

### ISSUE THREAD

**Issue by matoken** [takumakanari/cronv#37]
```
$ printf "* * * * *\tcommand" | ./cronv 
panic: Failed to analyze cron '* * * * *        command': syntax error in year field: 'command'

goroutine 1 [running]:
panic
		../../../src/libgo/go/runtime/panic.go:554
main.main
		/home/mk/go/src/github.com/takumakanari/cronv/cronv/main.go:33
```

It is a workaround.
```
$ printf "* * * * *\tcommand" | tr -s '\t' ' ' | ./cronv
```

**Comment by takumakanari** [comment]
Thank you for your report. I'll check it later.

**Comment by takumakanari** [comment]
Hi @matoken, This issue was fixed in the latest version. 
Thanks.
